spring.application.name=full-site
spring.datasource.url=jdbc:postgresql://localhost:5432/dbsb
spring.datasource.username=postgres
spring.datasource.password=Admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY}
spring.cloud.aws.region.static=us-east-2
aws.s3.bucket-name=${AWS_BUCKET_NAME}

# At least 256-bit hex string is required by JJWT 0.13+ for HS256
application.security.jwt.secret-key=${JWTS}
application.security.jwt.expiration=86400000

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
